/****
 * @bpautogenerated: IMPORTANT NOTE: do not modify this file, it was generated by `ts-openapi-boilerplate`
 ****/
import express, { NextFunction, Request, Response, Router } from "express";

interface RouteConfig<
  A = unknown,
  B = unknown,
  C = unknown,
  D = unknown,
  E = unknown,
  F = unknown,
  G = unknown,
  H = unknown,
  I = unknown,
  J = unknown
> {
  method: A;
  operationId: B;
  expressPath: C;
  openapiPath: D;
  pathParams?: E;
  responses?: F;
  successResponses?: I;
  requestBody?: G;
  queryParams?: H;
  headers?: J;
}

interface RequestHandler<T extends RouteConfig> {
  (
    req: Request<
      T["pathParams"],
      T["responses"],
      T["requestBody"],
      T["queryParams"]
    > & {
      apiHeaders: T["headers"];
    },
    res: Response<T["successResponses"]>,
    next: NextFunction
  ): void;
}

const typedRouter = (
  router: Router,
  ...routerMiddleware: express.RequestHandler[]
) => {
  return {
    get: <T extends RouteConfig<"get">>(
      url: T["expressPath"],
      handler: RequestHandler<T>,
      endpointMiddleware?: express.RequestHandler[]
    ) => {
      router.get(
        url as string,
        ...routerMiddleware,
        ...(endpointMiddleware || []),
        setApiHeaders,
        handler as express.RequestHandler
      );
    },
    post: <T extends RouteConfig<"post">>(
      url: T["expressPath"],
      handler: RequestHandler<T>,
      endpointMiddleware?: express.RequestHandler[]
    ) => {
      router.post(
        url as string,
        ...routerMiddleware,
        ...(endpointMiddleware || []),
        setApiHeaders,
        handler as express.RequestHandler
      );
    },
    put: <T extends RouteConfig<"put">>(
      url: T["expressPath"],
      handler: RequestHandler<T>,
      endpointMiddleware?: express.RequestHandler[]
    ) => {
      router.put(
        url as string,
        ...routerMiddleware,
        ...(endpointMiddleware || []),
        setApiHeaders,
        handler as express.RequestHandler
      );
    },
    patch: <T extends RouteConfig<"patch">>(
      url: T["expressPath"],
      handler: RequestHandler<T>,
      endpointMiddleware?: express.RequestHandler[]
    ) => {
      router.patch(
        url as string,
        ...routerMiddleware,
        ...(endpointMiddleware || []),
        setApiHeaders,
        handler as express.RequestHandler
      );
    },
    delete: <T extends RouteConfig<"delete">>(
      url: T["expressPath"],
      handler: RequestHandler<T>,
      endpointMiddleware?: express.RequestHandler[]
    ) => {
      router.delete(
        url as string,
        ...routerMiddleware,
        ...(endpointMiddleware || []),
        setApiHeaders,
        handler as express.RequestHandler
      );
    },
    baseRouter: () => router,
  };
};

/**
 * Very simple middleware that simply replicates the `headers` object into a new field names `apiHeaders`.
 * This way we can have a typed version of the request headers, without changing the default type for the `headers` field.
 */
function setApiHeaders(
  req: express.Request,
  res: express.Response,
  next: express.NextFunction
) {
  req.apiHeaders = req.headers;
  next();
}

/**
 * Converts a path in OpenApi format into Express format
 * @param openapiPath e.g., /account-access-consents/{ConsentId}/auth/{AnotherId}
 * @returns e.g., /account-access-consents/:ConsentId/auth/:AnotherId
 */
const openapiToExpressPath = (openapiPath: string) =>
  openapiPath.replace(/{([^}]*)}/g, ":$1");

export { openapiToExpressPath, typedRouter, RouteConfig, RequestHandler };
